export const TEAMS = ['Blackpool',
 'Liverpool',
 'Manchester United',
 'Stoke City',
 'Fulham',
 'Blackburn Rovers',
 'Manchester City',
 'Sunderland',
 'Bolton Wanderers',
 'Arsenal',
 'Birmingham City',
 'Tottenham Hotspur',
 'West Bromwich Albion',
 'West Ham United',
 'Aston Villa',
 'Everton',
 'Newcastle United',
 'Wigan Athletic',
 'Wolverhampton Wanderers',
 'Chelsea',
 'Swansea City',
 'Queens Park Rangers',
 'Norwich City',
 'Reading',
 'Southampton',
 'Crystal Palace',
 'Cardiff City',
 'Hull City',
 'Burnley',
 'Leicester City',
 'Watford',
 'AFC Bournemouth',
 'Middlesbrough',
 'Brighton and Hove Albion',
 'Huddersfield Town',
 'Sheffield United',
 'Leeds United'];