export const TEAMS = [
 'Liverpool',
 'Manchester United',
 'Fulham',
 'Manchester City',
 'Arsenal',
 'Tottenham Hotspur',
 'West Bromwich Albion',
 'West Ham United',
 'Aston Villa',
 'Everton',
 'Newcastle United',
 'Wolverhampton Wanderers',
 'Chelsea',
 'Norwich City',
 'Southampton',
 'Crystal Palace',
 'Burnley',
 'Leicester City',
 'Watford',
 'AFC Bournemouth',
 'Middlesbrough',
 'Brighton and Hove Albion',
 'Sheffield United',
 'Leeds United'].sort();